# Generated by Django 2.2.2 on 2019-06-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('make', models.CharField(max_length=256)),
                ('model', models.CharField(max_length=256)),
                ('year', models.IntegerField(default=0)),
            ],
        ),
    ]
